<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-VA3AMHQ" failures="1" tests="6" name="tests.ErrorValidationTest" time="12.389" errors="0" timestamp="2025-02-24T17:20:22 EET" skipped="0">
  <testcase classname="tests.ErrorValidationTest" name="fillWrongCheckoutPageInfo" time="2.149"/>
  <testcase classname="tests.ErrorValidationTest" name="loginWrongCredentials" time="1.835"/>
  <testcase classname="tests.ErrorValidationTest" name="fillWrongCheckoutPageInfo" time="2.187"/>
  <testcase classname="tests.ErrorValidationTest" name="loginLockedUser" time="1.827"/>
  <testcase classname="tests.ErrorValidationTest" name="fillWrongCheckoutPageInfo" time="2.242"/>
  <testcase classname="tests.ErrorValidationTest" name="takeScreenShotOfFailedTest" time="2.149">
    <failure message="Intentionally failing this test to showcase screenshot feature." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Intentionally failing this test to showcase screenshot feature.
at org.testng.Assert.fail(Assert.java:111)
at tests.ErrorValidationTest.takeScreenShotOfFailedTest(ErrorValidationTest.java:64)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- takeScreenShotOfFailedTest -->
</testsuite> <!-- tests.ErrorValidationTest -->
